### ISSUE TITLE
при закрытии вкладки (on_close) где активирован плагин- выключать плагин

### ISSUE THREAD

**Issue by Alexey-T** [mix-7/cuda_clipboard_catcher#10]

**Comment by mix-7** [comment]
Связано с 

тест под линукс- креши · Issue #9 · mix-7/cuda_clipboard_catcher
https://github.com/mix-7/cuda_clipboard_catcher/issues/9

надо и здесь, и там отслеживать невозможность вставки

Я подумаю еще, как это лучше реализовать.

Дела в том, что on_close:

1 срабатывает для всех (любых) вкладок, а не только с одной той,  с которой работает плагин.
Насколько я понял, нельзя подписаться на событие on_close для конкретной вкладки (хэндлера)

2 может (?) входить в конфликт с on_timer

Скорее всего, нужно поставить 
try - exception для вставки из буфера обмена
и при невозможности вставки выключать плагин, посылая сообщение 
в Statusbar Message и в консоль.

**Comment by Alexey-T** [comment]
try-except даст грязный код. надо ловить все ошибки даже без try. try в плагинах - на пожарный случай. try спрячет креши которые мы хотим увидеть и поправить.

**Comment by Alexey-T** [comment]
> срабатывает для всех (любых) вкладок, а не только с одной той, с которой работает плагин.

да. вы должны сравнить ed_self.h  и хендл от ed_current.h

>Насколько я понял, нельзя подписаться на событие on_close для конкретной вкладки (хэндлера)

да

**Comment by mix-7** [comment]
Сделал обработку on_close
Проверяю в ней ed_self ==  ed_current
Если закрыта наша вкладка, выключаю плагин.

Файлы закоммитил
