### ISSUE TITLE
при фокусировании других табов (on_focus), убирать в статусе синий флаг

### ISSUE THREAD

**Issue by Alexey-T** [mix-7/cuda_clipboard_catcher#11]

**Comment by mix-7** [comment]
Это нужно как напоминание о включенном режиме, так как копирование возможно из других вкладок редактора, не только из других программ.
Чтобы не забыть, что действия с буфером обмена в других вкладках могут привести к вставке текста во вкладку, для который был запущен Clipboard Catcher.

**Comment by Alexey-T** [comment]
okay
