### ISSUE TITLE
идея- вместо синего флага в статусе, показать цвет в ui tab title

### ISSUE THREAD

**Issue by Alexey-T** [mix-7/cuda_clipboard_catcher#12]
ed.set_prop(PROP_TAB_COLOR, 0xaa0000)

**Comment by Alexey-T** [comment]
если "зайдет" то восстанавлиивать предыдущий цвет тоже надо

**Comment by mix-7** [comment]
Да, спасибо, тоже думал об этом.
Но надо восстанавливать цвет таба, кроме того, таб может быть за пределами окна CudaText
Добавил вывод сообщения в консоль и в статус для какого таба и файла включен плагин как напоминание.
