### ISSUE TITLE
name 'ed_current' is not defined

### ISSUE THREAD

**Issue by veksha** [mix-7/cuda_clipboard_catcher#13]
Traceback (most recent call last):
  File "F:\MySSDPrograms\cudatext\py\cuda_clipboard_catcher\__init__.py", line 95, in on_close
    if (ed_self == ed_current): # закрыли нашу вкладку
NameError: name 'ed_current' is not defined
ERROR: Exception in CudaText for on_close: NameError: name 'ed_current' is not defined

после запуска Куды открыл новую вкладку и закрыл. получил ошибку.

**Comment by mix-7** [comment]
Исправил в 17:12, добавил проверку того, что плагин Сlipboard Сatcher был запущен:

```
    def on_close(self, ed_self):
        global COPY_CLIPS
        global ed_current
        if COPY_CLIPS: # проверяем на закрытие вкладку только, если плагин был запущен (тогда ed_current определен)
            if (ed_self == ed_current): # закрыли нашу вкладку

```

Скачайте, плз, __init__.py https://github.com/mix-7/cuda_tabs_list_print/blob/main/__init__.py
Прошу извинить за регрессию.
(Кстати, большое спасибо за идею с timer_proc!)

**Comment by mix-7** [comment]
@Alexey-T , как закоммитить новую редакцию 

init.py https://github.com/mix-7/cuda_tabs_list_print/blob/main/__init__.py
в ваш репозиторий плагинов Cuda Text?

**Comment by Alexey-T** [comment]
обновил в аддонах.

**Comment by veksha** [comment]
благодарю.

**Comment by mix-7** [comment]
Спасибо!

Если вдруг будет новая версия, нужно делать Pull request?

**Comment by Alexey-T** [comment]
полОжите в свое репо. и потом мне напишите в гитхаб (куда угодно) с тегированием имени - @Alexey-T
