### ISSUE TITLE
How to make the plugin to be auto-deactivated temporarily when copy is from the document itself

### ISSUE THREAD

**Issue by George1825** [mix-7/cuda_clipboard_catcher#15]
Plugin will auto-insert text into the the document which was focused on activation. This is convenient. However, when I make a copy from the the document itself, plugin will make a replace of selection too. The results is the composition will be changed.
We can close it by hand, but is it possible to make the plugin to be auto-deactivated temporarily when copy is from the document itself?
Thanks!

**Comment by mix-7** [comment]
Hi, 

You can split your tab vertically
In the left part, paste from the clipboard using the plugin,
in the right, select and copy.

You can also configure a shortcut in the Command palette to easily enable/disable the plugin.
