### ISSUE TITLE
составьте readme/readme_ru.txt , и я переведу его на инглиш

### ISSUE THREAD

**Issue by Alexey-T** [mix-7/cuda_clipboard_catcher#3]

**Comment by mix-7** [comment]
Плагин Cudatext clipboard catcher предназначен для вставки теrстовых фрагментов из буфера обмена в редактируемый текст в редакторе CudaText.
Для активации плагина нужно выбрать в меню Plugins - Clipboard Catcher Toggle.
При этом справа в строке статуса появится синий прямоугольник.
После этого копировать текст в буфер обмена для вставки.
Текст вставляется после курсора или вместо выделенного фрагмента.
Копировать  можно из других программ, других вкладок или даже из этой же вкладки, если разделить ее на две с помощью меню View - Split tab - Vertically.

**Comment by Alexey-T** [comment]
readme/readme.txt

```
Clipboard Catcher - plugin for CudaText.
Plugin is intended to insert clipboard contents into current editor's text.
To activate the plugin, call menu item in "Plugins - Clipboard Catcher Toggle".
After you do it, plugin must show blue rectangle in the statusbar.
After that, you can copy fragments to clipboard.
Clipboard contents is inserted after the caret, or over the selected text.
You can 'copy' from different programs, different CudaText ui-tabs, or from
the same ui-tab if it is "splitted" (CudaText menu "View / Split tab").

Author: mix-7, https://github.com/mix-7
License: MIT
```

**Comment by mix-7** [comment]
Сделал, спасибо:

cuda_clipboard_catcher/readme/readme.txt at main · mix-7/cuda_clipboard_catcher
https://github.com/mix-7/cuda_clipboard_catcher/blob/main/readme/readme.txt

Issue можно закрывать?

**Comment by Alexey-T** [comment]
можно
