### ISSUE TITLE
черный цвет на синем не читается

### ISSUE THREAD

**Issue by Alexey-T** [mix-7/cuda_clipboard_catcher#8]
![Screenshot_2023-08-08_13-09-36](https://github.com/mix-7/cuda_clipboard_catcher/assets/4154978/d5557675-ad0d-4736-a814-c2986685bf67)

можно получить текущий цвет из темы.
введите в консоль

=app_proc(PROC_THEME_UI_DICT_GET,'')

**Comment by mix-7** [comment]
Могу вообще убрать текст
Синий прямоугольник заметен
А режим вставки лучше видеть

**Comment by Alexey-T** [comment]
можно убрать текст. и сделать более узкий прямоуголник.

**Comment by mix-7** [comment]
ОК, посмотрю, как задается размер ячейки статуса, исправлю

**Comment by Alexey-T** [comment]
* STATUSBAR_SET_CELL_SIZE: Sets width of cell. Param "value": int.

**Comment by mix-7** [comment]
Исправил: задал ширину 25 пикселей (?), без текста, синий квадратик в правом конце статусбара
Закоммитил __init__.py

**Comment by mix-7** [comment]
> * STATUSBAR_SET_CELL_SIZE: Sets width of cell. Param "value": int.

спасибо!
