### ISSUE TITLE
тест под линукс- креши

### ISSUE THREAD

**Issue by Alexey-T** [mix-7/cuda_clipboard_catcher#9]
выделил текст в консоли. скопировал. получил креш.

![Screenshot_2023-08-08_13-13-36](https://github.com/mix-7/cuda_clipboard_catcher/assets/4154978/4460329c-b346-4ce7-9075-f843e70df37b)

**Comment by Alexey-T** [comment]
похоже  что хендл (из которого делается обьект Editor) кривой. попробуте перед копированием в кклипборд, вывести `print(ed_my.get_filename())`

**Comment by mix-7** [comment]
Попробовал в консоли:


>>> print(ed_my.get_filename())
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'ed_my' is not defined
ERROR: Exception in CudaText: NameError: name 'ed_my' is not defined

В коде:


    print(ed_my.get_filename())
NameError: name 'ed_my' is not defined. Did you mean: 'h_my'?
ERROR: Exception in CudaText for run: NameError: name 'ed_my' is not defined

То же для print(app.ed_my.get_filename())

**Comment by Alexey-T** [comment]
ed_current я имел в виду.

**Comment by Alexey-T** [comment]
```
        h_my = app.ed.get_prop(app.PROP_HANDLE_SELF, '') # запомним, откуда, из какой вкладки был вызван Clipboard catcher
        ed_current =  app.Editor(h_my) 
```

вы запомнили хендл . один раз при активации. и потом я закрыл вкладку - хендл сразу стал инвалидным. потому и креш.

надо - запоминать хендл периодически.

**Comment by Alexey-T** [comment]
можете еще и проверить валидность хендла. для этого пройдите по всем вкладкам через ed_handles()  , получите в цикле реальные два хендла (активный и пассивный редактор) и найдите ваш хендл.

**Comment by mix-7** [comment]
```
        h_my = app.ed.get_prop(app.PROP_HANDLE_SELF, '') # запомним, откуда, из какой вкладки был вызван Clipboard catcher
        ed_current =  app.Editor(h_my)        # запомним, откуда, из какой вкладки был вызван Clipboard catcher  
        print(ed_current.get_filename())
```
        
Вывод пустой!

**Comment by Alexey-T** [comment]
нет же. вы вывели принт при активации плагина. надо-

- сделать принт в do_insert
- закрыть начальную вкладку после активации плагина
- проверить что принт крешится

**Comment by mix-7** [comment]
> Вывод пустой!
Потому что у меня вкладка не была сохранена в файле

> * проверить что принт крешится

Т.е. надо поставить 
try: 
except
В except проверять существование вкладки, 
если вкладка закрыта, выводить предупреждение в консоль?
И прописать это предупреждение не закрывать вкладку в readme?

Или сделать реакцию на закрытие данной вкладки ?

Ведь нам не нужно вставлять текст в другие вкладки, это чревато испортить там текст.
Да, вкладка может быть закрыта случайно.

**Comment by mix-7** [comment]
> можете еще и проверить валидность хендла. для этого пройдите по всем вкладкам через ed_handles() , получите в цикле реальные два хендла (активный и пассивный редактор) и найдите ваш хендл.

Если хэндла нет - вкладка закрыта, надо остановить плагин и вывести предупреждение в консоль?

**Comment by Alexey-T** [comment]
>Или сделать реакцию на закрытие данной вкладки ?

вот это.

>Если хэндла нет - вкладка закрыта, надо остановить плагин и вывести предупреждение в консоль?

да. таккая проверка не помешает даже если вы среагировали на on_close.

**Comment by mix-7** [comment]
ОК, 
добавлю on_close
и проверку на пропадание хэндла

**Comment by Alexey-T** [comment]
проверку валидности хендла - делать на ваше усммотрение. по идее должно и без нее быть ок.
